# Generated by Django 5.1.2 on 2024-12-07 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(default='general', max_length=100, unique=True),
        ),
    ]
