# Generated by Django 5.1.2 on 2025-02-08 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
